name: CI

on:

  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  CI:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20.17.0

      - name: Instalação do Mocha para teste
        run: |
          cd devops-basico/aula-02/conversao-temperatura/src;
          npm install -g mocha;
          npm install

      - name: Execução do teste
        run: mocha devops-basico/aula-02/conversao-temperatura/src/test/convert.js
        
      - name: Construção imagem Docker
        uses: docker/build-push-action@v6.9.0
        with:
          context: devops-basico/aula-02/conversao-temperatura/src
          file: devops-basico/aula-02/conversao-temperatura/src/Dockerfile
          push: true
          tags: |
            bffsantos/aula-conversao-temparatura:v1
            bffsantos/aula-conversao-temparatura:latest
        

